name: CI/CD Simples com AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push_ecr:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do Código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura as Credenciais AWS
      # Usa as secrets do repositório para configurar o ambiente
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login no ECR
      # Usa a AWS CLI para autenticar o Docker no ECR
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Configura o Docker Buildx
      - name: Configura o Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Construção e Push da Imagem para o ECR
      - name: Build e Push da Imagem Docker para o ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_REPOSITORY_URI }}:latest
            ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          # O ECR_REPOSITORY_URI já inclui o endereço completo da AWS